// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$0 from "./actions/chat/ai-response.ts";
import * as $$$$$$$$$1 from "./actions/chat/stream-ai-response.ts";
import * as $$$$$$$$$$$0 from "./apps/deco/htmx.ts";
import * as $$$$$$$$$$$1 from "./apps/site.ts";
import * as $$$0 from "./loaders/brands/brands.ts";
import * as $$$1 from "./loaders/categories/tree.ts";
import * as $$$2 from "./loaders/collections/list.ts";
import * as $$$3 from "./loaders/inventory/getInventoryBySkus.ts";
import * as $$$4 from "./loaders/inventory/getInventoryBySkusAndWarehouse.ts";
import * as $$$5 from "./loaders/logistics/getSalesChannelById.ts";
import * as $$$6 from "./loaders/logistics/listPickupPoints.ts";
import * as $$$7 from "./loaders/logistics/listPickupPointsByLocation.ts";
import * as $$$8 from "./loaders/logistics/listSalesChannel.ts";
import * as $$$9 from "./loaders/logistics/listStockByStore.ts";
import * as $$$10 from "./loaders/masterdata/searchDocuments.ts";
import * as $$$11 from "./loaders/orders/getOrderAnalisys.ts";
import * as $$$12 from "./loaders/orders/getOrderById.ts";
import * as $$$13 from "./loaders/orders/listAllOrders.ts";
import * as $$$14 from "./loaders/orders/orderItems.ts";
import * as $$$15 from "./loaders/product/productBySlug.ts";
import * as $$$16 from "./loaders/product/productListByCollection.ts";
import * as $$$17 from "./loaders/product/productListByFacets.ts";
import * as $$$18 from "./loaders/product/productListByProductIds.ts";
import * as $$$19 from "./loaders/product/productListBySkuIds.ts";
import * as $$$20 from "./loaders/product/productListByTerm.ts";
import * as $$$21 from "./loaders/product/relatedProducts.ts";
import * as $$$22 from "./loaders/promotion/getCouponByCode.ts";
import * as $$$23 from "./loaders/promotion/getPromotionById.ts";
import * as $$$24 from "./loaders/promotion/listCoupons.ts";
import * as $$$25 from "./loaders/promotion/listPromotions.ts";
import * as $$$26 from "./loaders/warehouse/listWarehouses.ts";
import * as $$$$$$0 from "./sections/Chat.tsx";
import * as $$$$$$1 from "./sections/Component.tsx";
import * as $$$$$$2 from "./sections/Home.tsx";
import * as $$$$$$3 from "./sections/Theme/Theme.tsx";

const manifest = {
  "loaders": {
    "site/loaders/brands/brands.ts": $$$0,
    "site/loaders/categories/tree.ts": $$$1,
    "site/loaders/collections/list.ts": $$$2,
    "site/loaders/inventory/getInventoryBySkus.ts": $$$3,
    "site/loaders/inventory/getInventoryBySkusAndWarehouse.ts": $$$4,
    "site/loaders/logistics/getSalesChannelById.ts": $$$5,
    "site/loaders/logistics/listPickupPoints.ts": $$$6,
    "site/loaders/logistics/listPickupPointsByLocation.ts": $$$7,
    "site/loaders/logistics/listSalesChannel.ts": $$$8,
    "site/loaders/logistics/listStockByStore.ts": $$$9,
    "site/loaders/masterdata/searchDocuments.ts": $$$10,
    "site/loaders/orders/getOrderAnalisys.ts": $$$11,
    "site/loaders/orders/getOrderById.ts": $$$12,
    "site/loaders/orders/listAllOrders.ts": $$$13,
    "site/loaders/orders/orderItems.ts": $$$14,
    "site/loaders/product/productBySlug.ts": $$$15,
    "site/loaders/product/productListByCollection.ts": $$$16,
    "site/loaders/product/productListByFacets.ts": $$$17,
    "site/loaders/product/productListByProductIds.ts": $$$18,
    "site/loaders/product/productListBySkuIds.ts": $$$19,
    "site/loaders/product/productListByTerm.ts": $$$20,
    "site/loaders/product/relatedProducts.ts": $$$21,
    "site/loaders/promotion/getCouponByCode.ts": $$$22,
    "site/loaders/promotion/getPromotionById.ts": $$$23,
    "site/loaders/promotion/listCoupons.ts": $$$24,
    "site/loaders/promotion/listPromotions.ts": $$$25,
    "site/loaders/warehouse/listWarehouses.ts": $$$26,
  },
  "sections": {
    "site/sections/Chat.tsx": $$$$$$0,
    "site/sections/Component.tsx": $$$$$$1,
    "site/sections/Home.tsx": $$$$$$2,
    "site/sections/Theme/Theme.tsx": $$$$$$3,
  },
  "actions": {
    "site/actions/chat/ai-response.ts": $$$$$$$$$0,
    "site/actions/chat/stream-ai-response.ts": $$$$$$$$$1,
  },
  "apps": {
    "site/apps/deco/htmx.ts": $$$$$$$$$$$0,
    "site/apps/site.ts": $$$$$$$$$$$1,
  },
  "name": "site",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
