// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$0 from "./actions/chat/ai-response.ts";
import * as $$$$$$$$$1 from "./actions/chat/stream-ai-response.ts";
import * as $$$$$$$$$$$0 from "./apps/deco/htmx.ts";
import * as $$$$$$$$$$$1 from "./apps/site.ts";
import * as $$$0 from "./loaders/brands/brands.ts";
import * as $$$1 from "./loaders/call-center/aboutUs.ts";
import * as $$$2 from "./loaders/call-center/exchangesAndReturns.ts";
import * as $$$3 from "./loaders/call-center/frequentlyAskedQuestions.ts";
import * as $$$4 from "./loaders/call-center/purchasesAndOrders.ts";
import * as $$$5 from "./loaders/call-center/storeLocations.ts";
import * as $$$6 from "./loaders/categories/tree.ts";
import * as $$$7 from "./loaders/masterdata/searchDocuments.ts";
import * as $$$8 from "./loaders/product/productBySlug.ts";
import * as $$$9 from "./loaders/product/productListByCollection.ts";
import * as $$$10 from "./loaders/product/productListByFacets.ts";
import * as $$$11 from "./loaders/product/productListByProductIds.ts";
import * as $$$12 from "./loaders/product/productListBySkuIds.ts";
import * as $$$13 from "./loaders/product/productListByTerm.ts";
import * as $$$14 from "./loaders/product/relatedProducts.ts";
import * as $$$$$$0 from "./sections/Chat.tsx";
import * as $$$$$$1 from "./sections/Component.tsx";
import * as $$$$$$2 from "./sections/Home.tsx";
import * as $$$$$$3 from "./sections/Theme/Theme.tsx";

const manifest = {
  "loaders": {
    "site/loaders/brands/brands.ts": $$$0,
    "site/loaders/call-center/aboutUs.ts": $$$1,
    "site/loaders/call-center/exchangesAndReturns.ts": $$$2,
    "site/loaders/call-center/frequentlyAskedQuestions.ts": $$$3,
    "site/loaders/call-center/purchasesAndOrders.ts": $$$4,
    "site/loaders/call-center/storeLocations.ts": $$$5,
    "site/loaders/categories/tree.ts": $$$6,
    "site/loaders/masterdata/searchDocuments.ts": $$$7,
    "site/loaders/product/productBySlug.ts": $$$8,
    "site/loaders/product/productListByCollection.ts": $$$9,
    "site/loaders/product/productListByFacets.ts": $$$10,
    "site/loaders/product/productListByProductIds.ts": $$$11,
    "site/loaders/product/productListBySkuIds.ts": $$$12,
    "site/loaders/product/productListByTerm.ts": $$$13,
    "site/loaders/product/relatedProducts.ts": $$$14,
  },
  "sections": {
    "site/sections/Chat.tsx": $$$$$$0,
    "site/sections/Component.tsx": $$$$$$1,
    "site/sections/Home.tsx": $$$$$$2,
    "site/sections/Theme/Theme.tsx": $$$$$$3,
  },
  "actions": {
    "site/actions/chat/ai-response.ts": $$$$$$$$$0,
    "site/actions/chat/stream-ai-response.ts": $$$$$$$$$1,
  },
  "apps": {
    "site/apps/deco/htmx.ts": $$$$$$$$$$$0,
    "site/apps/site.ts": $$$$$$$$$$$1,
  },
  "name": "site",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
